/*
 * NPCDefView.java
 */

package npcdef;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.swing.JDialog;
import javax.swing.JFrame;

import npcdef.resources.NPCDefinition;
import npcdef.resources.NPCXML;
import npcdef.resources.NPCXML.NPC;
import npcdef.resources.OutPutConsole;

import org.jdesktop.application.Action;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.SingleFrameApplication;

/**
 * The application's main frame.
 */
public class NPCDefView extends FrameView {

    public NPCDefView(SingleFrameApplication app) {
        super(app);

        initComponents();
        NPCIDField.setText("");
        NAMESTRING.setText("");
        EXAMINESTRING.setText("");
        HEALSTRING.setText("");
       // IMMUNESTRING.setText("");
       // SPAWNSTRING.setText("");
        ClearButton.setLabel("Clear");
        System.setOut(new OutPutConsole(jTextArea1, jScrollPane1));
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = NPCDefApp.getApplication().getMainFrame();
            aboutBox = new NPCDefAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        NPCDefApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NAME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EXAMINE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        HEALTH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ERROR = new javax.swing.JLabel();
        NAMESTRING = new javax.swing.JLabel();
        EXAMINESTRING = new javax.swing.JLabel();
        HEALSTRING = new javax.swing.JLabel();
        POISON = new javax.swing.JCheckBox();
        AGGRESSIVE = new javax.swing.JCheckBox();
        SPAWN = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ClearButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NPCIDLoad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NPCIDField = new java.awt.Label();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem SaveMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();

        mainPanel.setName("mainPanel"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(NPCDefView.class);
        NAME.setText(resourceMap.getString("NAME.text")); // NOI18N
        NAME.setName("NAME"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        EXAMINE.setText(resourceMap.getString("EXAMINE.text")); // NOI18N
        EXAMINE.setName("EXAMINE"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        HEALTH.setText(resourceMap.getString("HEALTH.text")); // NOI18N
        HEALTH.setName("HEALTH"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        ERROR.setText(resourceMap.getString("ERROR.text")); // NOI18N
        ERROR.setName("ERROR"); // NOI18N

        NAMESTRING.setText(resourceMap.getString("NAMESTRING.text")); // NOI18N
        NAMESTRING.setName("NAMESTRING"); // NOI18N

        EXAMINESTRING.setText(resourceMap.getString("EXAMINESTRING.text")); // NOI18N
        EXAMINESTRING.setName("EXAMINESTRING"); // NOI18N

        HEALSTRING.setText(resourceMap.getString("HEALSTRING.text")); // NOI18N
        HEALSTRING.setName("HEALSTRING"); // NOI18N

        POISON.setText(resourceMap.getString("POISON.text")); // NOI18N
        POISON.setName("POISON"); // NOI18N

        AGGRESSIVE.setText(resourceMap.getString("AGGRESSIVE.text")); // NOI18N
        AGGRESSIVE.setName("AGGRESSIVE"); // NOI18N

        SPAWN.setName("SPAWN"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(EXAMINE, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(HEALTH, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(ERROR, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(POISON, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AGGRESSIVE))
                            .addComponent(SPAWN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NAMESTRING)
                            .addComponent(EXAMINESTRING)
                            .addComponent(HEALSTRING))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(NAMESTRING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EXAMINE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EXAMINESTRING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HEALTH, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HEALSTRING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AGGRESSIVE)
                    .addComponent(POISON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SPAWN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ERROR, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        ClearButton.setLabel(resourceMap.getString("ClearButton.label")); // NOI18N
        ClearButton.setName("ClearButton"); // NOI18N
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        NPCIDLoad.setText(resourceMap.getString("NPCIDLoad.text")); // NOI18N
        NPCIDLoad.setName("NPCIDLoad"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        NPCIDField.setName("NPCIDField"); // NOI18N
        NPCIDField.setText(resourceMap.getString("NPCIDField.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NPCIDLoad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(NPCIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NPCIDLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(NPCIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(NPCDefView.class, this);
        SaveMenuItem.setAction(actionMap.get("SaveFile")); // NOI18N
        SaveMenuItem.setName("SaveMenuItem"); // NOI18N
        fileMenu.add(SaveMenuItem);

        exitMenuItem1.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem1.setName("exitMenuItem1"); // NOI18N
        fileMenu.add(exitMenuItem1);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        NPCIDLoad.setText("");
        NPCIDField.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private final String[] INVALID = {
    		"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S",
    		"T", "U", "V", "W", "X", "Y", "Z"
    };

    private final String[] INVALID_VARIABLES = {
        "`", "~", "!", "@", "#" , "$" , "%", "^", "&", "(", "*", ")", "_",
        "-", " ", " ", "[", "]", "{", "}", ";", ":", "'", ",", "<", ".", ">", "/", "?", "+", "="
    };

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(NPCIDLoad.getText().isEmpty()) {
            NPCIDField.setText("This field must be filled in.");
            return;
        }
        for(String invalid : INVALID) {
            if(NPCIDLoad.getText().toLowerCase().contains(invalid.toLowerCase())) {
                NPCIDField.setText("Incompatable characters.");
                return;
            }
        }
        for(String invalid : INVALID_VARIABLES) {
            if(NPCIDLoad.getText().toLowerCase().contains(invalid.toLowerCase())) {
                NPCIDField.setText("Incompatable characters.");
                return;
            }
        }
        //LOAD
        for(NPC n : NPCXML.defs) {
            if(n.getID() == Integer.parseInt(NPCIDLoad.getText())) {
                System.out.println("NPC Name: "+n.getName());
                System.out.println("NPC Id: "+n.getID());
                System.out.println("CombatLevel: "+n.getCombatLevel());
                System.out.println("TileSize: "+n.getTileSize());
                System.out.println("MaxHealth: "+n.getMaxHealth());
                System.out.println("SpawnRate: "+((n.getSpawnTimer() >= 60) ? ((n.getSpawnTimer() / 60) +" mins") : n.getSpawnTimer() +" secs"));
                System.out.println("PoisonImmunity: "+n.isImmuneToPoison());
                return;
            }
        }
        System.out.println("NPC Definition doesn't exist.");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    	synchronized(this) {
	    		// TODO add your handling code here:
	        boolean canContinue = true;
	
	        NAMESTRING.setText("");
	        EXAMINESTRING.setText("");
	       // IMMUNESTRING.setText("");
	        //SPAWNSTRING.setText("");
	       // SPAWNSTRING.setText("");
	
	        for(String invalid : INVALID_VARIABLES) {
	            if(NAME.getText().toLowerCase().contains(invalid) || NAME.getText().isEmpty()) {
	                canContinue = false;
	                NAMESTRING.setText("Name Error");
	            }
	        }
	
	        for(String invalid : INVALID_VARIABLES) {
	            if(HEALTH.getText().toLowerCase().contains(invalid) || HEALTH.getText().isEmpty()) {
	                canContinue = false;
	                HEALSTRING.setText("Health Error");
	            }
	        }
	
	        if((Integer) SPAWN.getValue() < 0) {
	             canContinue = false;
	        }
	
	        if(!canContinue) {
	            ERROR.setText("Please fix the indicated fields.");
	            return;
	        }
	
	        //load
	        int id = Integer.parseInt(NAME.getText());
	        String name = NPCDefinition.forID(id).getName();
	        int combat = NPCDefinition.forID(id).getCombatLevel();
	        List<NPC> toAdd = new ArrayList<NPC>();
	        try {
		        /*for(NPC n : NPCXML.defs)
		            if(combat == NPCDefinition.forID(n.getID()).getCombatLevel() && NPCDefinition.forID(n.getID()).getName().toLowerCase().equals(name.toLowerCase()))
		                NPCXML.defs.remove(n);*/
		
		        for (Map.Entry<Integer, NPCDefinition> potential : NPCDefinition.npcs.entrySet()) {
		            if(combat == potential.getValue().getCombatLevel() && potential.getValue().getName().toLowerCase().equals(name.toLowerCase())) {
		                toAdd.add(new NPC(potential.getKey(), POISON.isSelected(), Integer.parseInt(HEALTH.getText()), (Integer) SPAWN.getValue()));
		            }
		        }
	        } catch(Exception e) {
	           ERROR.setText("Error");
	           return;
	        }
	        for(NPC n : toAdd)
	        	NPCXML.defs.add(n);
	        NAMESTRING.setText("");
	        EXAMINESTRING.setText("");
	        HEALSTRING.setText("");
	        NAME.setText("");
	        EXAMINE.setText("");
	        HEALTH.setText("");
	        POISON.setSelected(false);
	        SPAWN.setValue(0);
	        ERROR.setText("NPC Definition Added.");
    	}
    }

    @Action
    public void SaveFile() {
       // NPCXML.saveXML();
        NPCXML.createBinary();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AGGRESSIVE;
    private java.awt.Button ClearButton;
    private javax.swing.JLabel ERROR;
    private javax.swing.JTextField EXAMINE;
    private javax.swing.JLabel EXAMINESTRING;
    private javax.swing.JLabel HEALSTRING;
    private javax.swing.JTextField HEALTH;
    private javax.swing.JTextField NAME;
    private javax.swing.JLabel NAMESTRING;
    private java.awt.Label NPCIDField;
    private javax.swing.JTextField NPCIDLoad;
    private javax.swing.JCheckBox POISON;
    private javax.swing.JSpinner SPAWN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables


    private JDialog aboutBox;
}
